### ISSUE TITLE
MS SQL server?

### ISSUE THREAD

**Issue by eQvin** [nayeemazad/DMS#1]
Do you use MS SQL Server. How to conntect and create DB. After loggin I have error with DB.

**Comment by cstechsandip** [comment]
Where is the DB

**Comment by eQvin** [comment]
Dude, I found how to solve this problem. 
1. You need change DB connection in Startup.cs  = > services.AddDbContext
2. Download VS 2017 + MS SQL Server Developer 2017 + MS SQL Server Management Studio 17.*
3. Create Db in Management Studio. And tables. Users , Categories and etc.
4. Write connection to your Db in services.AddDbContext. Like me 
services.AddDbContext<DMSContext>(options =>
                options.UseSqlServer("Server=SWIFT-PC; " +
                "Database = dmcdb;" +
                //" Initial Catalog= DMS; " +
                "Integrated Security = True; User Id=sa;Password=timur;  ", b=>b.UseRowNumberForPaging()));
